import type { Scenario } from "./dto";

type FixtureRun = Scenario["runs"][number];
type FixtureNode = Scenario["nodes"][number];

const representativeRuns: FixtureRun[] = [
  {
    id: "run_01J8R4NQX6K3PV4W0A1H2Z7M9C",
    name: "App\\Jobs\\GenerateMonthlyInvoices",
    status: "completed",
    connection: "redis",
    queue: "billing",
    attemptCount: 2,
    triggeredAt: "4:01:21 PM",
    queueDuration: "312ms",
    duration: "15.3s",
  },
  {
    id: "run_01J8R4H9S9J12V04CNH6F6JQ3M",
    name: "App\\Jobs\\SendInvoiceMail",
    status: "completed",
    connection: "redis",
    queue: "mail",
    attemptCount: 1,
    triggeredAt: "4:01:26 PM",
    queueDuration: "488ms",
    duration: "4.6s",
  },
  {
    id: "run_01J8R47YYNA4GFVDMTQ9P59BJW",
    name: "App\\Jobs\\RefreshRevenueReport",
    status: "running",
    connection: "database",
    queue: "reports",
    attemptCount: 1,
    triggeredAt: "4:00:58 PM",
    queueDuration: "1.2s",
    duration: "22.8s",
  },
  {
    id: "run_01J8R3XK1YV76N3Q51RPXQ0VC2",
    name: "App\\Jobs\\ImportLegacyOrders",
    status: "failed",
    connection: "sqs",
    queue: "imports",
    attemptCount: 3,
    triggeredAt: "3:59:42 PM",
    queueDuration: "85ms",
    duration: "41.2s",
  },
  {
    id: "run_01J8R3RXZ6A7J19G4Y53CXF7F4",
    name: "App\\Jobs\\ReconcilePayouts",
    status: "queued",
    connection: "redis",
    queue: "default",
    attemptCount: 0,
    triggeredAt: "3:58:11 PM",
    queueDuration: "—",
    duration: "—",
  },
];

const runs: FixtureRun[] = [
  ...representativeRuns,
  ...Array.from({ length: 25 }, (_, index): FixtureRun => {
    const number = index + 6;

    return {
      id: `run_fixture_${String(number).padStart(2, "0")}`,
      name: `App\\Jobs\\BackgroundJob${String(number).padStart(2, "0")}`,
      status: index % 2 === 0 ? "running" : "queued",
      connection: "redis",
      queue: "default",
      attemptCount: index % 2 === 0 ? 1 : 0,
      triggeredAt: `3:${String(57 - index).padStart(2, "0")}:00 PM`,
      queueDuration: index % 2 === 0 ? "120ms" : "—",
      duration: index % 2 === 0 ? "3.4s" : "—",
    };
  }),
];

const retryNodes: FixtureNode[] = [
  {
    id: "run_01J8R4NQX6K3PV4W0A1H2Z7M9C",
    runId: runs[0].id,
    kind: "run",
    label: "GenerateMonthlyInvoices",
    level: 0,
    offsetMs: 0,
    durationMs: 15300,
    status: "completed",
    isPartial: true,
    timelineEvents: [
      { name: "Triggered", offsetMs: 0 },
      { name: "Dequeued", offsetMs: 312 },
      { name: "Finished", offsetMs: 15_300 },
    ],
    metadata: { traceId: "fda8d9cf9d53e8845fd0738b8407731d", connection: "redis", queue: "billing" },
  },
  {
    id: "attempt_run_01J8R4NQX6K3PV4W0A1H2Z7M9C_1",
    parentId: runs[0].id,
    runId: runs[0].id,
    kind: "attempt",
    label: "Attempt 1",
    level: 1,
    offsetMs: 312,
    durationMs: 2050,
    status: "failed",
    isError: true,
    timelineEvents: [
      { name: "Started", offsetMs: 312 },
      { name: "Failed", offsetMs: 2_362 },
    ],
    exception: {
      class: "Illuminate\\Database\\DeadlockException",
      message: "Deadlock found when trying to get lock; retry transaction",
      frames: [
        { file: "app/Jobs/GenerateMonthlyInvoices.php", line: 58, call: "GenerateMonthlyInvoices->handle()" },
        { file: "vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php", line: 124, call: "CallQueuedHandler->call()" },
      ],
    },
    metadata: { attempt: 1, spanId: "d139ef778ebe35d8" },
  },
  {
    id: "span_17ba81b7da8f8b64",
    parentId: "attempt_run_01J8R4NQX6K3PV4W0A1H2Z7M9C_1",
    runId: runs[0].id,
    kind: "query",
    label: "select * from `customers` where `invoiced_at` is null limit 100",
    level: 2,
    offsetMs: 520,
    durationMs: 46,
    status: "completed",
    sql: "select * from `customers` where `invoiced_at` is null limit 100",
    metadata: { "db.system": "mysql", "db.namespace": "skyline_fixture", "server.address": "127.0.0.1" },
  },
  {
    id: "attempt_run_01J8R4NQX6K3PV4W0A1H2Z7M9C_2",
    parentId: runs[0].id,
    runId: runs[0].id,
    kind: "attempt",
    label: "Attempt 2",
    level: 1,
    offsetMs: 3150,
    durationMs: 12150,
    status: "completed",
    metadata: { attempt: 2, spanId: "9adb4c77c49de9aa" },
  },
  {
    id: "span_83d7c6ca42be40ef",
    parentId: "attempt_run_01J8R4NQX6K3PV4W0A1H2Z7M9C_2",
    runId: runs[0].id,
    kind: "query",
    label: "select * from `customers` where `invoiced_at` is null limit 100",
    level: 2,
    offsetMs: 3420,
    durationMs: 38,
    status: "completed",
    sql: "select * from `customers` where `invoiced_at` is null limit 100",
    metadata: { "db.system": "mysql", "db.operation.name": "SELECT", "db.namespace": "skyline_fixture" },
  },
  {
    id: "span_4f24adb545b26d31",
    parentId: "attempt_run_01J8R4NQX6K3PV4W0A1H2Z7M9C_2",
    runId: runs[0].id,
    kind: "query",
    label: "insert into `invoices` (`customer_id`, `total`, `created_at`) values (?, ?, ?)",
    level: 2,
    offsetMs: 4100,
    durationMs: 82,
    status: "completed",
    sql: "insert into `invoices` (`customer_id`, `total`, `created_at`) values (?, ?, ?)",
    metadata: { "db.system": "mysql", "db.operation.name": "INSERT", "db.namespace": "skyline_fixture" },
  },
  {
    id: runs[1].id,
    parentId: "attempt_run_01J8R4NQX6K3PV4W0A1H2Z7M9C_2",
    runId: runs[1].id,
    kind: "run",
    label: "SendInvoiceMail",
    level: 2,
    offsetMs: 5150,
    durationMs: 5050,
    status: "completed",
    metadata: { traceId: "fda8d9cf9d53e8845fd0738b8407731d", connection: "redis", queue: "mail" },
  },
  {
    id: "attempt_run_01J8R4H9S9J12V04CNH6F6JQ3M_1",
    parentId: runs[1].id,
    runId: runs[1].id,
    kind: "attempt",
    label: "Attempt 1",
    level: 3,
    offsetMs: 5638,
    durationMs: 4562,
    status: "completed",
    metadata: { attempt: 1, spanId: "aa64d2c5803a4c97" },
  },
  {
    id: "span_a866b446b5df56e3",
    parentId: "attempt_run_01J8R4H9S9J12V04CNH6F6JQ3M_1",
    runId: runs[1].id,
    kind: "query",
    label: "select * from `invoices` where `id` = ? limit 1",
    level: 4,
    offsetMs: 5780,
    durationMs: 24,
    status: "completed",
    sql: "select * from `invoices` where `id` = ? limit 1",
    metadata: { "db.system": "mysql", "db.operation.name": "SELECT" },
  },
];

const successNodes: FixtureNode[] = retryNodes.filter((node) =>
  [runs[1].id, "attempt_run_01J8R4H9S9J12V04CNH6F6JQ3M_1", "span_a866b446b5df56e3"].includes(node.id),
).map((node, index) => ({
  ...node,
  parentId: index === 0 ? undefined : node.parentId,
  level: index,
  offsetMs: Math.max(0, node.offsetMs - 5150),
}));

const failureNodes: FixtureNode[] = [
  {
    id: runs[3].id,
    runId: runs[3].id,
    kind: "run",
    label: "ImportLegacyOrders",
    level: 0,
    offsetMs: 0,
    durationMs: 41200,
    status: "failed",
    isError: true,
    metadata: { traceId: "2dd468224ab1e45c7da1921b2ef74ad1", connection: "sqs", queue: "imports" },
  },
  {
    id: "attempt_run_01J8R3XK1YV76N3Q51RPXQ0VC2_3",
    parentId: runs[3].id,
    runId: runs[3].id,
    kind: "attempt",
    label: "Attempt 3",
    level: 1,
    offsetMs: 35000,
    durationMs: 6200,
    status: "failed",
    isError: true,
    exception: {
      class: "UnexpectedValueException",
      message: "Order currency GBP does not match the import account currency USD",
      frames: [
        { file: "app/Jobs/ImportLegacyOrders.php", line: 91, call: "ImportLegacyOrders->mapOrder()" },
        { file: "app/Jobs/ImportLegacyOrders.php", line: 47, call: "ImportLegacyOrders->handle()" },
      ],
    },
    metadata: { attempt: 3, spanId: "f2a6424cf9b0c130" },
  },
  {
    id: "span_c17a8ce47c5bb1ea",
    parentId: "attempt_run_01J8R3XK1YV76N3Q51RPXQ0VC2_3",
    runId: runs[3].id,
    kind: "query",
    label: "select * from `accounts` where `id` = ? limit 1",
    level: 2,
    offsetMs: 35200,
    durationMs: 31,
    status: "completed",
    sql: "select * from `accounts` where `id` = ? limit 1",
    metadata: { "db.system": "pgsql", "db.operation.name": "SELECT" },
  },
];

export const scenarios: Scenario[] = [
  { key: "retry", label: "Retry + child Run", selectedRunId: runs[0].id, runs, nodes: retryNodes },
  { key: "success", label: "Child Run success", selectedRunId: runs[1].id, runs, nodes: successNodes },
  { key: "failure", label: "Final failure", selectedRunId: runs[3].id, runs, nodes: failureNodes },
];
