#!/usr/bin/env sh
set -eu

cd "$(dirname "$0")"
php -r "file_exists('.env') || copy('.env.example', '.env'); file_exists('database/database.sqlite') || touch('database/database.sqlite');"
php artisan migrate:fresh --force --ansi
php artisan skyline:overhead
